#!/usr/bin/env bash
# Gets Apache running and display Hello Holberton when querrying its root
echo '<!DOCTYPE html>
<html>
<head>
    <title>Hello Holberton</title>
</head>
<body>
    <h1>Hello Holberton</h1>
</body>
</html>' > index.html
echo "Hello Holberton" > /var/www/html/index.html

# Step 2: Create Dockerfile
echo 'FROM httpd:latest
COPY ./index.html /usr/local/apache2/htdocs/' > Dockerfile

# Step 3: Build Docker image
docker build -t my-apache-image .

# Step 4: Run Docker container
docker run -d -p 8080:80 --name my-apache-container my-apache-image

