#!/usr/bin/env bash
# script of task 0 but using less lines
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx stop
service nginx restart
