#!/usr/bin/env bash
#configures nginx server to respond to status code '404',
#returns a custom Error 404 page containing "Ceci n'est pas une page"

sudo apt-get update 
sudo apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" >/etc/nginx/html/404.html

print %s "server {
    listen 80;
    listen[::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
    location /redirect_me {
        return 301 http://youtube.com/;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
